### ISSUE TITLE
[LINUX] Callback returns wrong result, but Windows is fine

### ISSUE THREAD

**Issue by rimpy-custom** [philippj/SteamworksPy#62]
I have this code:
```
import os
import sys

if sys.version_info >= (3, 8):
  os.add_dll_directory(os.getcwd()) # Required since Python 3.8

from steamworks import STEAMWORKS # Import main STEAMWORKS class

def checkCallbacks(obj):
  obj.run_forever(0.5)
    
def call_me(result):
  print("Result =", result.result)
  print("ID =", result.publishedFileId)
  
if __name__ == '__main__':

  steamworks = STEAMWORKS()
  steamworks.initialize()

  from threading import Thread
  th = Thread(target=checkCallbacks, args=(steamworks,))
  th.start()

  steamworks.Workshop.SetItemSubscribedCallback(call_me)
  steamworks.Workshop.SubscribeItem(2336610918)
```
  
On Windows I get (as it should):
```
Result = 1
ID = 2336610918
```

on Linux:
```
Result = 1860236288
ID = 10035667476286537729
```
On linux code always returns the same ID `10035667476286537729` all the time, but Result may change (I got atleast four different results, even negative).
 I compiled code with x64 libsteam_api.so, if that matter, used 1.50 SDK. Debian 10 system.
 Steam itself is i386, I was unable to find 64bit version for Linux.

**Comment by rimpy-custom** [comment]
Update on that. Recompilled with SDK 1.47, the same issue.

**Comment by philippj** [comment]
I have not yet tested it on Linux. Once I resolve #61 I will get back to you about this.

**Comment by philippj** [comment]
Resolved by #72

**Comment by rimpy-custom** [comment]
I am still getting issues. To make things clear, here is reproducible example: https://rentry.co/tskkp
Output on Windows 10:
```
Item subscribed (<steamworks.structs.RemoteStorageSubscribePublishedFileResult_t object at 0x0000020DA6979C40>,) {}
9 1
Item unsubscribed (<steamworks.structs.RemoteStorageUnsubscribePublishedFileResult_t object at 0x0000020DA6979C40>,) {}
1 1
```
Output on Fedora 36:
```
Item subscribed (<steamworks.structs.RemoteStorageSubscribePublishedFileResult_t object at 0x7f05abal5c40>,) {}
-1415941056 4294967305
Item unsubscribed (<steamworks.structs.RemoteStorageUnsubscribePublishedFileResult_t object at 0x7f05abal5c40>,) {}
-1415941056 4294967297
```
Both OS are 64 bit, python is 64bit also. Looks like somethhing wrong with ctypes?
